<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
رمزگشایی از روایت‌های خاموش: نجات دادن جوانان از چنگال خودکشی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این چالش، شما به عنوان یک دانشمند داده با قلبی مشتاق برای نجات جان‌ها، ماموریت دارید که داده‌های گزارش‌دهی ملی مرگ‌های خشونت‌آمیز را تجزیه و تحلیل کنید. این داده‌ها شامل خلاصه‌ای از گزارش‌های انتظامی و پزشکی قانونی می‌باشد که مربوط به خودکشی‌های انجام‌شده توسط جوانان است. هدف از این تجزیه و تحلیل، شناسایی عوامل کلیدی است که می‌تواند به پیشگیری از خودکشی در آینده کمک کند.
داده‌های ارائه‌شده شامل روایت‌های مختلف و غیرقابل شناسایی است که توسط کارشناسان دولتی تهیه شده‌اند. این داده‌ها خلاصه‌ای از ماجراهای تلخی هستند که باید با دقت و حساسیت بررسی شوند.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer 
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
مجموعه داده آموزشی شامل ۳۰۰۰ سطر است که در جدول زیر، توضیحات هر ستون آمده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|uid|شناسه‌ی یکتای هر مورد|
|NarrativeLE|گزارش خلاصه‌ای از اطلاعات مامور قانون|
|NarrativeCME|خلاصه‌ای از اطلاعات گزارش پزشک قانونی/معاینه‌کننده پزشکی|
|DepressedMood|در آن زمان افسرده بوده یا خیر (۰ یا ۱)|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    مجموعه داده آزمایش نیز مانند مجموعه آموزش است با این تفاوت که ستون <code>DepressedMood</code> که متغیر هدف مسئله است را در خود ندارد. مجموعه داده آزمایش ۵۰۰ سطر دارد.
</font>
</p>


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از دادگان آموزشی را به عنوان دادگان اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [13]:
train_data = pd.read_csv('../data/train.csv')
train_data

uid                                        NarrativeLE  \
0     astm  V was a XX XX found unresponsive and hanging i...   
1     eqeq  The V is an XX XX. The V called his girlfriend...   
2     arpf  V is a XX XX who died by suicide via multiple ...   
3     ffal  Police were dispatched for a sick assist/ poss...   
4     dyqf  Victim XX died of unspecified causes with an u...   
...    ...                                                ...   
2995  begx  V was XXXX. V was found lying on the bed at hi...   
2996  coxo  V was a XX, XX. [DC notes that the V is XX]Per...   
2997  cqrl  V was found hanging by a rope in the garage by...   
2998  fftl  Officers responded to the report of a suicide ...   
2999  dvlk  Law Enforcement were dispatched to the residen...   

                                           NarrativeCME  DepressedMood  
0     V was a XX XX found unresponsive and hanging i...              0  
1     DC NOTES: EVIDENCE OF RECENT ALCOHOL USE; RECE...              1  
2     V is a XX XX who died by suicide via multiple ...              0  
3     V is a XX XX who was found unresponsive in an ...              0  
4     Victim XX XX died from Self-Inflicted Intraora...              0  
...                                                 ...            ...  
2995  V was XXXX. V was found lying on the bed at hi...              0  
2996  V was a XX, XX. [DC notes that the V is XX]Per...              0  
2997  V was a XX XX XX whose manner of death was sui...              0  
2998  The Victim (V) was a XX XX XX XX.  V was disco...              1  
2999  This XX XX was found hanging with a rope from ...              0  

[3000 rows x 4 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [14]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   uid            3000 non-null   object
 1   NarrativeLE    3000 non-null   object
 2   NarrativeCME   3000 non-null   object
 3   DepressedMood  3000 non-null   int64 
dtypes: int64(1), object(3)
memory usage: 93.9+ KB


In [15]:
train_data.isnull().sum()    

uid              0
NarrativeLE      0
NarrativeCME     0
DepressedMood    0
dtype: int64

In [16]:
texts = train_data['NarrativeLE'].fillna("") + " " + train_data['NarrativeCME'].fillna("")
labels = train_data['DepressedMood']

In [17]:
labels

0       0
1       1
2       0
3       0
4       0
       ..
2995    0
2996    0
2997    0
2998    1
2999    0
Name: DepressedMood, Length: 3000, dtype: int64

In [18]:
texts

0       V was a XX XX found unresponsive and hanging i...
1       The V is an XX XX. The V called his girlfriend...
2       V is a XX XX who died by suicide via multiple ...
3       Police were dispatched for a sick assist/ poss...
4       Victim XX died of unspecified causes with an u...
                              ...                        
2995    V was XXXX. V was found lying on the bed at hi...
2996    V was a XX, XX. [DC notes that the V is XX]Per...
2997    V was found hanging by a rope in the garage by...
2998    Officers responded to the report of a suicide ...
2999    Law Enforcement were dispatched to the residen...
Length: 3000, dtype: object

In [19]:
train_data.head()

uid                                        NarrativeLE  \
0  astm  V was a XX XX found unresponsive and hanging i...   
1  eqeq  The V is an XX XX. The V called his girlfriend...   
2  arpf  V is a XX XX who died by suicide via multiple ...   
3  ffal  Police were dispatched for a sick assist/ poss...   
4  dyqf  Victim XX died of unspecified causes with an u...   

                                        NarrativeCME  DepressedMood  
0  V was a XX XX found unresponsive and hanging i...              0  
1  DC NOTES: EVIDENCE OF RECENT ALCOHOL USE; RECE...              1  
2  V is a XX XX who died by suicide via multiple ...              0  
3  V is a XX XX who was found unresponsive in an ...              0  
4  Victim XX XX died from Self-Inflicted Intraora...              0

In [20]:
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

In [21]:
labels

array([0, 1, 0, ..., 0, 1, 0])

In [22]:
vectorizer = CountVectorizer(max_features=5000) 
X = vectorizer.fit_transform(texts).toarray()

In [23]:
vectorizer

CountVectorizer(max_features=5000)

In [24]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

In [26]:
X_train, X_test

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]))

In [27]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [28]:
class TextDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


train_dataset = TextDataset(X_train_tensor, y_train_tensor)
test_dataset = TextDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)


In [29]:
class SimpleNN(nn.Module):
    def __init__(
		self,
  		input_dim: str,
		output_dim: str
	):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, output_dim)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)
        
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return self.softmax(x)

input_dim = X_train.shape[1] 
output_dim = len(set(labels))
model = SimpleNN(input_dim, output_dim) 

In [30]:

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


epochs = 50
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    
    print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(train_loader)}, Accuracy: {100 * correct / total}%")


Epoch 1/50, Loss: 0.6300605618953705, Accuracy: 66.20833333333333%
Epoch 2/50, Loss: 0.5268973139921824, Accuracy: 77.66666666666667%
Epoch 3/50, Loss: 0.4369573831558228, Accuracy: 87.875%
Epoch 4/50, Loss: 0.398923773765564, Accuracy: 91.875%
Epoch 5/50, Loss: 0.39379575292269386, Accuracy: 91.91666666666667%
Epoch 6/50, Loss: 0.36063135027885435, Accuracy: 95.45833333333333%
Epoch 7/50, Loss: 0.3519999865690867, Accuracy: 96.25%
Epoch 8/50, Loss: 0.3497653623421987, Accuracy: 96.29166666666667%
Epoch 9/50, Loss: 0.34522061347961425, Accuracy: 96.875%
Epoch 10/50, Loss: 0.3412230336666107, Accuracy: 97.33333333333333%
Epoch 11/50, Loss: 0.33962536334991456, Accuracy: 97.41666666666667%
Epoch 12/50, Loss: 0.3386196545759837, Accuracy: 97.5%
Epoch 13/50, Loss: 0.33773246526718137, Accuracy: 97.58333333333333%
Epoch 14/50, Loss: 0.3375715005397797, Accuracy: 97.58333333333333%
Epoch 15/50, Loss: 0.3367416715621948, Accuracy: 97.66666666666667%
Epoch 16/50, Loss: 0.3362682255109151, Accu

In [31]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy: {100 * correct / total}%")


Test Accuracy: 75.33333333333333%


In [32]:
model

SimpleNN(
  (fc1): Linear(in_features=5000, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
  (relu): ReLU()
  (softmax): Softmax(dim=1)
)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: center;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|DepressedMood|در آن زمان افسرده بوده یا خیر (۰ یا ۱)|
    
</font>
</div>



<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل یک ستون با اسم <i>DepressedMood</i> است و ۵۰۰ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، مقادیر ستون <i>DepressedMood</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: center;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|DepressedMood|
|-----|
|1|
|0|
|0|
|0|
|1|

</font>
</div>



In [33]:
test_data = pd.read_csv('../data/test.csv')
test_data

uid                                        NarrativeLE  \
0    azjz  V (XX XX) was found by his mother hanging by a...   
1    cwke  V was XXXX. V was found at her residence unres...   
2    eqcg  V was XXXX. V was found at her boyfriend's res...   
3    abgm  A XX XX (V) was found with a GSW to the head i...   
4    cwwt  LE summary:V Demographics data is consistent w...   
..    ...                                                ...   
495  abbe  V (XX XX) poisoned himself in his garage.   V ...   
496  dxof  Victim XX XX died of a self-intentional gunsho...   
497  fhqz  V is a XX XX who died by suicide via acute com...   
498  duwv  The V was a XX, XX XX XX. The V called 911 at ...   
499  arnx  Victim XX XX died from intentional hanging fro...   

                                          NarrativeCME  
0    The V, a XX, XX, was staying at his father's h...  
1    V was XXXX. V was found in her residence suffe...  
2    V was XXXX. V was found in another's residence...  
3    V is a XX XX with a medical history of bipolar...  
4    XX, XX, Lived w/. - parents/family COD:  Gunsh...  
..                                                 ...  
495  V (XX XX) poisoned himself in his garage.   V ...  
496  Victim XX XX died of a self-intentional gunsho...  
497  V is a XX XX who died by suicide via acute com...  
498  The V was a XX XX. The V's family called LE to...  
499  Victim XX XX died from intentional hanging fro...  

[500 rows x 3 columns]